for i in ~/.vim ~/.vimrc ~/.gvimrc; do [ -e $i ] && mv $i $i.old; done
git clone git://github.com/csexton/viceroy.git ~/.vim
for i in vimrc gvimrc; do [ -e $i ] && ln -s ~/.vim/$i ~/.$i; done


echo '                                                                  _______'
echo '                                                                LLLLLLLLLLL'
echo '                                                            __LLLLLLLLLLLLLL'
echo '                                                           LLLLLLLLLLLLLLLLL'
echo '                                                         _LLLLLLLLLLLLLLLLLL'
echo '                                                        LLLLLLLLLLLLLLLLLLLL'
echo '                                                      _LLLLLLLLLLLLLLLLLLLLL'
echo '                                                      LLLLLLLLLLLLLLLLLLLLLL'
echo '                                              L     _LLLLLLLLLLLLLLLLLLLLLLL'
echo '                                             LL     LLLLLL~~~LLLLLLLLLLLLLL'
echo '                                            _L    _LLLLL      LLLLLLLLLLLLL'
echo '                                            L~    LLL~        LLLLLLLLLLLLL'
echo '                                           LL   _LLL        _LL   LLLLLLLL'
echo '       Welcome to Viceroy                 LL    LL~         ~~     ~LLLLLL'
echo '                                          L   _LLL_LLLL___         _LLLLLL'
echo '                                         LL  LLLLLLLLLLLLLL      LLLLLLLL'
echo '                                         L  LLLLLLLLLLLLLLL        LLLLLL'
echo '                                        LL LLLLLLLLLLLLLLLL        LLLLL~'
echo '                  LLLLLLLL_______       L _LLLLLLLLLLLLLLLL     LLLLLLLL'
echo '                         ~~~~~~~LLLLLLLLLLLLLLLLLLLLLLLLL~       LLLLLL'
echo '                       ______________LLL  LLLLLLLLLLLLLL ______LLLLLLLLL_'
echo '                   LLLLLLLLLLLLLLLLLLLL  LLLLLLLL~~LLLLLLL~~~~~~   ~LLLLLL'
echo '             ___LLLLLLLLLL __LLLLLLLLLLLLL LLLLLLLLLLLLL____       _LLLLLL_'
echo '          LLLLLLLLLLL~~   LLLLLLLLLLLLLLL   LLLLLLLLLLLLLLLLLL     ~~~LLLLL'
echo '      __LLLLLLLLLLL     _LLLLLLLLLLLLLLLLL_  LLLLLLLLLLLLLLLLLL_       LLLLL'
echo '     LLLLLLLLLLL~       LLLLLLLLLLLLLLLLLLL   ~L ~~LLLLLLLLLLLLL      LLLLLL'
echo '   _LLLLLLLLLLLL       LLLLLLLLLLLLLLLLLLLLL_  LL      LLLLLLLLL   LLLLLLLLL'
echo '  LLLLLLLLLLLLL        LLLLLLLLLLLLL~LLLLLL~L   LL       ~~~~~       ~LLLLLL'
echo ' LLLLLLLLLLLLLLL__L    LLLLLLLLLLLL_LLLLLLL LL_  LL_            _     LLLLLL'
echo 'LLLLLLLLLLLLLLLLL~     ~LLLLLLLL~~LLLLLLLL   ~L  ~LLLL          ~L   LLLLLL~'
echo 'LLLLLLLLLLLLLLLL               _LLLLLLLLLL    LL  LLLLLLL___     LLLLLLLLLL'
echo 'LLLLLLLLLLLLLLLL              LL~LLLLLLLL~     LL  LLLLLLLLLLLL   LLLLLLL~'
echo 'LLLLLLLLLLLLLLLL_  __L       _L  LLLLLLLL      LLL_ LLLLLLLLLLLLLLLLLLLLL'
echo ' LLLLLLLLLLLLLLLLLLLL        L~  LLLLLLLL      LLLLLLL~LLLLLLLLLLLLLLLL~'
echo '  LLLLLLLLLLLLLLLLLLLL___L_ LL   LLLLLLL       LLLL     LLLLLLLLLLLLLL'
echo '   ~~LLLLLLLLLLLLLLLLLLLLLLLL     LLLLL~      LLLLL        ~~~~~~~~~'
echo '           LLLLLLLLLLLLLLLLLL_ _   LLL       _LLLLL'
echo '               ~~~~~~LLLLLLLLLL~             LLLLLL'
echo '                         LLLLL              _LLLLLL'
echo '                         LLLLL    L     L   LLLLLLL'
echo '                          LLLLL__LL    _L__LLLLLLLL'
echo '                          LLLLLLLLLL  LLLLLLLLLLLL'
echo '                           LLLLLLLLLLLLLLLLLLLLLL'
echo '                            ~LLLLLLLLLLLLLLLLL~~'
echo '                               LLLLLLLLLLLLL'
echo '                                 ~~~~~~~~~'
